os:
  - osx

language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - npm i imagemin-mozjpeg@6.0.0

install:
  - npm install

before_script:
  - git submodule update --remote --merge

script:
  - hexo clean
  - hexo g
after_script:
  - cd public
  - git init
  - git config user.name "qizhenjun"
  - git config user.email "15388511@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/bolind86/bolind86.github.io.git

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - 15388511@qq.com
  on_success: always
  on_failure: always